#!/bin/bash
# Source this script into the script you use to feed lemonbar
# And use the colors there

bg="#343031"
fg="#c0bfbf"
blk="#393637"
bblk="#575556"
red="#654c51"
grn="#7f8281"
ylw="#8d7766"
blu="#5b697e"
mag="#7b6b75"
cyn="#7d8592"
wht="#c0bfbf"
bred="#654c51"
bgrn="#7f8281"
bylw="#8d7766"
bblu="#5b697e"
bmag="#7b6b75"
bcyn="#7d8592"
bwht="#c0bfbf"
